export const questionsStore = [
    {
        question: 'Kogo ściął Ned Stark w pierwszym odcinku "Gry o tron"?',
        a:'Złodzieja',
        b:'Dezertera z Nocnej Straży',
        c:'Jednego z "dzikich" zza Muru',
        d:'Strażnika',
        true: 'Dezertera z Nocnej Straży',
    },
    {
        question: 'Jak się nazywa miecz, który Aryia Stark dostała od Jona Snowa',
        a:'Igła',
        b:'Żądło',
        c:'Ostrze',
        d:'Anioł',
        true:'Igła',
    },
    {
        question: 'Kto podarował Daenerys smocze jaja?',
        a:'Khal Drogo',
        b:'Illyrio Mopatis',
        c:'Jorah Mormont',
        d:'Viserysa Targaryenów',
        true:'Illyrio Mopatis',
    },
    {
        question: 'Co stało się z Damą, wilkorem Sansy Stark?',
        a:'Zabił ją Joffrey',
        b:'Zabił ją Ned Stark',
        c:'Uciekła',
        d:'Zabił ją  Theona Greyjoy',
        true:'Zabił ją Ned Stark',
    },
    {
        question: 'Jak mają na imię trzy smoki Daenerys?',
        a:'Drogon, Viserys, Aerys',
        b:'Drogon, Raphael, Viserys',
        c:'Drogon, Rhaegal, Viserion',
        d:'Drogon, Rhaegal, Nymeria',
        true:'Drogon, Rhaegal, Viserion',
    },
    {
        question: 'Ramsay Snow to:',
        a:'Brat Jona Snowa',
        b:`Bękart lorda Roose'a Boltona`,
        c:'Mąż Sansy Stark i wuj króla Joffreya',
        d:'Bratanek Neda Starka',
        true:`Bękart lorda Roose'a Boltona`,
    },
    {
        question: 'Co symbolizował warkocz Dothraków?',
        a:'Przynależność plemienną',
        b:'Czas od przegranego pojedynku',
        c:'Stopień wojskowy',
        d:'Wiek danej osoby',
        true:'Czas od przegranego pojedynku',
    },
    {
        question: 'Czym w czasie wojny zajmuje się Talisa Maegy, przyszła żona Roba Starka?',
        a:'Pomaga w polowej kuchni',
        b:'Jest łuczniczką i chce wstąpić do armii',
        c:'Opatruje rannych',
        d:'Jest służacą Robba Starka',
        true:'Opatruje rannych',
    },
    {
        question: 'W herbie którego rodu znajdował się jeleń?',
        a:'Baratheonów',
        b:'Lannisterów',
        c:'Starków',
        d:'Targaryenów',
        true:'Baratheonów',
    },
    {
        question: 'Jak wabił się wilkor Jona Snowa?',
        a:'Lód',
        b:'Duch',
        c:'Upiór',
        d:'Szary Wicher',
        true:'Duch',
    },

]

   
